name: crud_firebase
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0-279.3.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  fluttertoast: ^8.2.4
  firebase_core: ^2.25.4
  random_string: ^2.3.1
  cloud_firestore: ^4.15.6
  flutter_form_builder: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
